highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


url: http://jatinbhatia.github.io/
baseurl: http://jatinbhatia.github.io/
title: Jatin Bhatia
author: Jatin Bhatia
description: Homepage of Jatin Bhatia.
avatar: profile.png
email: myselfjatin91@gmail.com
github: JatinBhatia # username
twitter: JatinBhatia91
linkedin: jatin1511
#medium: TapasweniPathak

# needed for travis-ci build
exclude: [vendor]
