# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://JatinBhatia.github.io/
baseurl: http://JatinBhatia.github.io//
title: Jatin Bhatia
author: Jatin Bhatia
description: Homepage of Jatin Bhatia
avatar: profile.png
email: myselfjatin91@gmail.com
github: JatinBhatia # username
twitter: JatinBhatia91
linkedin: jatin1511
#Comment out if you don't want disqus 
#disqus: username

# needed for travis-ci build
exclude: [vendor]
